# Generated by Django 6.0.4 on 2026-04-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catefgoria',
            new_name='Categoria',
        ),
    ]
