# Generated by Django 4.2.30 on 2026-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_product_name_en_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionresponse',
            name='participant_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sessionresponse',
            name='preferred_overall',
            field=models.CharField(choices=[('A', 'Recomendação Robótica'), ('B', 'Recomendação Humanizada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sessionresponse',
            name='preferred_purchase',
            field=models.CharField(choices=[('A', 'Recomendação Robótica'), ('B', 'Recomendação Humanizada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sessionresponse',
            name='preferred_trust',
            field=models.CharField(choices=[('A', 'Recomendação Robótica'), ('B', 'Recomendação Humanizada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sessionresponse',
            name='preferred_understood',
            field=models.CharField(choices=[('A', 'Recomendação Robótica'), ('B', 'Recomendação Humanizada')], max_length=1),
        ),
    ]
